### PR TITLE
Update CONDUCT.md

### PR DESCRIPTION
**Pull request by grzracz**
- Proposals will be discussed in (VOTING):

1. Discord 
2. Slack 
3. Github Discussions 
4. Discourse 

I will edit this PR after voting. Please leave a comment to identify your name & organization with your GitHub account.

### CODE REVIEW

**Comment by grzracz** [comment]
I vote for Discord or Slack.
Grzegorz Raczek, Vestige

**Comment by johnalanwoods** [comment]
I vote for Slack.
John Woods, Algorand Foundation

**Comment by fergalwalsh** [comment]
I vote for Github Discussions or Slack.
Fergal Walsh, Tinyman

**Comment by urtho** [comment]
I don't love the tool but my vote is for **Discord**. 

Rationale:
- We do not need the reliable notifications that Slack provides and Discord lacks.  
- We'll be more and more transparent and Discord can provide both private and public rooms in one place
- Harder to decentralize admin ops for Slack

Urtho @ Algonode

**Comment by k13n** [comment]
I vote for Slack
Kevin Wellenzohn, Blockshake / Defly

**Comment by pbennett** [comment]
I like Slack a lot but 'free' use can get awkward at times for some, so Discord is probably best of the two.  Urtho also provides good justifications.

Patrick @ TxnLab/NFDomains

**Comment by robdmoore** [comment]
Prefer slack, OK with discord

**Comment by robdmoore** [comment]
(You can get away with the slack free tier issue by making someone a single channel guest in your workspace)

**Comment by yigitguler** [comment]
I vote for Slack or Github Discussions

**Comment by emg110** [comment]
I vote for Github discussions

Using Github tools in general (projects, wikis, discussions, voting App,...) will make everything more accessible and inclusive for devs, IMHO.
Remember many countries do not have access to Slack and Discord but almost everyone has access to Github

**Comment by algorandskiy** [comment]
1st choice: Slack
2nd choice: Github Discussions

Pavel @ Algorand Tech

Edit: order

**Comment by acfunk** [comment]
Discord

Funk, Lute Wallet

**Comment by palace22** [comment]
I vote for Discord

Giuseppe Palazzolo, Folks Finance

**Comment by pbennett** [comment]
if we're doing single votes now:
slack

**Comment by grzracz** [comment]
Single vote: Discord

**Comment by fergalwalsh** [comment]
Slack

**Pull request merged**
